/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2014 (12.0.5207)
    Source Database Engine Edition : Microsoft SQL Server Standard Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2014
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [Dadosadv_D1]
GO

/****** Object:  View [dbo].[CUSTO_FECHAMENTO_TRANSF_PARA_PROCESSO]    Script Date: 02/11/2017 06:27:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[CUSTO_FECHAMENTO_TRANSF_PARA_PROCESSO]
AS


SELECT 'MP_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MP'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'MP_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MP'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'MP_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MP'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'EB_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'EB'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'EB_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'EB'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'EB_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'EB'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'MX_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MX'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'MX_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MX'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'MX_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MX'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'PI_SEMI' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'PI_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'PI_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'ME_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'ME'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'ME_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'ME'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'ME_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'ME'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'PA_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'PA'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'PA_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'PA'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'PA_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'PA'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'MM_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MM'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'MM_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MM'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'MM_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MM'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'SV_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'SV'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'SV_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'SV'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'SV_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'SV'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL



SELECT 'MC_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MC'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL


SELECT 'MC_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MC'
AND B1_AGREGCU <> '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL = '99'
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL UNION ALL

SELECT 'MC_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010 WITH (NOLOCK)
INNER JOIN SB1010 AS SB1 WITH (NOLOCK) ON 
	B1_FILIAL = ''
AND B1_COD = D3_COD
AND B1_TIPO = 'MC'
AND B1_AGREGCU = '1'
AND SB1.D_E_L_E_T_ = ''
AND SB1.B1_APROPRI <> 'D'

WHERE D3_FILIAL IN( '01','06') 
AND SD3010.D_E_L_E_T_ = '' AND D3_ESTORNO= ''
AND D3_LOCAL NOT IN ('99')
AND YEAR(D3_EMISSAO) >= YEAR(GETDATE())- 2 
AND D3_TM = '900'

GROUP BY B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL 

GO

