/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2014 (12.0.5207)
    Source Database Engine Edition : Microsoft SQL Server Standard Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2014
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [Dadosadv_D1]
GO

/****** Object:  View [dbo].[CUSTO_FECHAMENTO_DEV_VENDAS_SD1]    Script Date: 02/11/2017 06:08:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[CUSTO_FECHAMENTO_DEV_VENDAS_SD1]
AS

--MP_GD
SELECT 'MP_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MP'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--WIP
SELECT 'MP_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'MP'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MP_TER
SELECT 'MP_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MP'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL
--EB_GD
SELECT 'EB_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'EB_GD'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--EB_WIP
SELECT 'EB_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'EB'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--EB_TER
SELECT 'EB_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'EB'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MX_GD
SELECT 'MX_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MX'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MX_WIP
SELECT 'MX_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'MX'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MX_TER
SELECT 'MX_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MX'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PI_SEMI
SELECT 'PI_SEMI' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PI_WIP
SELECT 'PI_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PI_TER
SELECT 'PI_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO IN ('PI','PE')
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--ME_GD
SELECT 'ME_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'ME'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--ME_WIP
SELECT 'ME_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'ME'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--ME_TER
SELECT 'ME_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'ME'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PA_GD
SELECT 'PA_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'PA'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PA_WIP
SELECT 'PA_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'PA'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--PA_TER
SELECT 'PA_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'PA'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL


UNION ALL

--MM_GD
SELECT 'MM_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MM'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MM_WIP
SELECT 'MM_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'MM'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MM_TER
SELECT 'MM_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MM'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL


UNION ALL

--SV_GD
SELECT 'SV_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'SV'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--SV_WIP
SELECT 'SV_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'SV'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--SV_TER
SELECT 'SV_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'SV'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL


UNION ALL

--MC_GD
SELECT 'MC_GD' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MC'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301'
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MC_WIP
SELECT 'MC_WIP' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL = '99'
AND B1_TIPO = 'MC'
AND B1_AGREGCU <> '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

UNION ALL

--MC_TER
SELECT 'MC_TER' as DESCRICAO
					,B1_COD
					,B1_DESC
					,B1_GRUPO
					,D1_TES
					,D1_DOC
					,D1_FORNECE	AS [CLIENTE]
					,A1_NREDUZ	AS [APELIDO]
					,LEFT(D1_DTDIGIT,6) AS PERIODO
					,ISNULL(SUM(D1_CUSTO),0) as valor
					,D1_FILIAL AS FILIAL 
FROM SD1010 WITH (NOLOCK)
	INNER JOIN SB1010 AS SB1 WITH (NOLOCK) 
	ON B1_FILIAL = '  '
	AND B1_COD = D1_COD 
	AND SB1.D_E_L_E_T_ = ''

JOIN SF4010 AS SF4  WITH (NOLOCK) 
		ON F4_FILIAL = ''
		AND F4_CODIGO = D1_TES
		AND SF4.D_E_L_E_T_ = ''

JOIN SA1010 AS SA1  WITH (NOLOCK) 
		ON SA1.A1_FILIAL = ''
		AND SA1.A1_COD	= D1_FORNECE
		AND SA1.A1_LOJA = D1_LOJA
		AND SA1.D_E_L_E_T_ = ''		
		
		
WHERE D1_FILIAL IN( '01','06')
AND SD1010.D_E_L_E_T_ = ''
AND D1_LOCAL NOT IN ('99')
AND B1_TIPO = 'MC'
AND B1_AGREGCU = '1'
AND F4_ESTOQUE = 'S'
AND F4_DUPLIC = 'S'
AND F4_PODER3 = 'N'
AND (UPPER(F4_TEXTO) LIKE '%DEV%' OR UPPER(F4_TEXTO) LIKE '%BRINDE%')
AND F4_TPMOV IN ('','09','06')
AND D1_DTDIGIT >= '20140301' 
GROUP BY B1_COD,B1_DESC,B1_GRUPO,D1_TES,F4_TEXTO,D1_DOC,D1_FORNECE,A1_NREDUZ,LEFT(D1_DTDIGIT,6), D1_FILIAL

GO

