/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2014 (12.0.5207)
    Source Database Engine Edition : Microsoft SQL Server Standard Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2014
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [Dadosadv_D1]
GO

/****** Object:  View [dbo].[CUSTO_FECHAMENTO_SALDOSB2]    Script Date: 02/11/2017 06:26:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO










CREATE VIEW [dbo].[CUSTO_FECHAMENTO_SALDOSB2]
AS


SELECT	T.DESCRICAO,
		T.GRUPO,
		T.CODIGO,
		T.CODIGO_ANTIGO,
		T.DESCRICAO_PRODUTO,
		SB1.B1_UM AS UM ,
		T.QUANTIDADE AS [QUANTIDADE_FECHAMENTO],
		T.VALOR AS [VALOR_FECHAMENTO],
		T.QUANTIDADE_ATUAL AS [QUANTIDADE_ATUAL],
		T.VALOR_ATUAL	AS [VALOR_ATUAL],
		SA1010.A1_GRPVEN AS SEGMENTO,
		T.FILIAL
 FROM 
(
SELECT  
'MP_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''

WHERE B2_FILIAL IN ('01','06') AND B1_TIPO = 'MP' AND B1_AGREGCU <> '1' 
AND NNR_CODIGO NOT IN ('99') 
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MP_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MP'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
 'MP_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MP'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

union all

SELECT  
'EB_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'EB'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'EB_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'EB'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
 'EB_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'EB'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

UNION ALL

SELECT  
'MX_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MX'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MX_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MX'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
 'MX_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MX'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

Union all

SELECT  
'PI_SEMI' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO in ('PI','PE')
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'PI_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO in ('PI','PE')
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'PI_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO in ('PI','PE')
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

union all

SELECT  
'ME_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = ('ME')
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'ME_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO ='ME'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'ME_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'ME'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

union all

SELECT  
'PA_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'PA'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'PA_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO ='PA'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'PA_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'PA'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL


union all

SELECT  
'MM_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MM'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MM_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO ='MM'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MM_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MM'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL

union all

SELECT  
'MC_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MC'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MC_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO ='MC'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'MC_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'MC'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_DESC,B1_CODCLI,B2_FILIAL


union all

SELECT  
'SV_GD' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'SV'
and B1_AGREGCU <> '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'SV_WIP' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO ='SV'
and B1_AGREGCU <> '1'
AND NNR_CODIGO = '99'
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
union all
SELECT  
'SV_TER' as DESCRICAO,B1_COD AS CODIGO ,ISNULL(SUM(B2_VFIM1),0) as VALOR ,ISNULL(SUM(B2_QFIM),0) as QUANTIDADE,ISNULL(SUM(B2_QATU),0) as [QUANTIDADE_ATUAL],ISNULL(SUM(B2_VATU1),0) as [VALOR_ATUAL],B1_GRUPO AS GRUPO,B1_CODANT AS CODIGO_ANTIGO,B1_DESC AS DESCRICAO_PRODUTO, B1_CODCLI AS COD_CLIENTE, B2_FILIAL AS FILIAL 
FROM SB2010 
LEFT JOIN SB1010 ON B1_COD = B2_COD AND B1_FILIAL = ''  AND SB1010.D_E_L_E_T_ = '' INNER JOIN NNR010 ON NNR_FILIAL = '' AND NNR_CODIGO = B2_LOCAL AND NNR010.D_E_L_E_T_ = ''
WHERE 
B2_FILIAL IN ('01','06')

AND B1_TIPO = 'SV'
and B1_AGREGCU = '1'
AND NNR_CODIGO NOT IN ('99')
AND SB2010.D_E_L_E_T_ = ''
GROUP BY B1_COD,B1_GRUPO,B1_CODANT,B1_DESC ,B1_GRUPO,B1_CODANT,B1_CODCLI,B2_FILIAL
) AS T
 
LEFT JOIN SA1010 ON T.COD_CLIENTE = A1_COD
AND SA1010.D_E_L_E_T_ = ''

INNER JOIN SB1010 AS SB1 ON SB1.B1_FILIAL = '' 
AND SB1.B1_COD = T.CODIGO
AND SB1.D_E_L_E_T_ = ''

--WHERE QUANTIDADE <> 0 AND QUANTIDADE_ATUAL <> 0 AND VALOR <> 0 AND VALOR_ATUAL <> 0



GO

