/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2014 (12.0.5207)
    Source Database Engine Edition : Microsoft SQL Server Standard Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2014
    Target Database Engine Edition : Microsoft SQL Server Standard Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [Dadosadv_D1]
GO

/****** Object:  View [dbo].[CUSTO_FECHAMENTO_PRODUCAO]    Script Date: 02/11/2017 06:25:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[CUSTO_FECHAMENTO_PRODUCAO]
AS

SELECT B1_TIPO + '_TER' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010
INNER JOIN SB1010 AS SB1 ON B1_FILIAL = ''
	AND B1_COD = D3_COD
	AND SB1.D_E_L_E_T_ =''

WHERE D3_FILIAL IN( '01','06') 
AND D3_OP <> '' 
AND D3_CF = ('PR0')
and B1_AGREGCU = '1'
AND SD3010.D_E_L_E_T_ = ''
AND D3_EMISSAO >= '20140301'  
AND D3_ESTORNO = ''
AND D3_SEQCALC <> ''
GROUP BY B1_TIPO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL

UNION ALL

SELECT B1_TIPO + '_WIP' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010
INNER JOIN SB1010 AS SB1 ON B1_FILIAL = ''
	AND B1_COD = D3_COD
	AND SB1.D_E_L_E_T_ =''

WHERE D3_FILIAL IN( '01','06') 
AND D3_OP <> '' 
AND D3_CF = ('PR0')
and B1_AGREGCU <> '1' AND D3_LOCAL = '99'
AND SD3010.D_E_L_E_T_ = ''
AND D3_EMISSAO >= '20140301'  
AND D3_ESTORNO = ''
AND D3_SEQCALC <> ''
GROUP BY B1_TIPO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL

UNION ALL

SELECT B1_TIPO + '_GD' as DESCRICAO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6) AS PERIODO,ISNULL(SUM(D3_CUSTO1),0) as valor,D3_FILIAL AS FILIAL 
FROM SD3010
INNER JOIN SB1010 AS SB1 ON B1_FILIAL = ''
	AND B1_COD = D3_COD
	AND SB1.D_E_L_E_T_ =''

WHERE D3_FILIAL IN( '01','06') 
AND D3_OP <> '' 
AND D3_CF = ('PR0')
and B1_AGREGCU <> '1' AND D3_LOCAL <> '99'
AND SD3010.D_E_L_E_T_ = ''
AND D3_EMISSAO >= '20140301'  
AND D3_ESTORNO = ''
AND D3_SEQCALC <> ''
GROUP BY B1_TIPO, B1_COD,B1_DESC,B1_GRUPO,D3_TM,D3_DOC,LEFT(D3_EMISSAO,6),D3_FILIAL
GO

